// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNfiWDgpT7qmcAlFG6DREFaru-NZOupkQ',
    appId: '1:554766211865:web:7cace5e9c45d4e7fa90388',
    messagingSenderId: '554766211865',
    projectId: 'notes-app-b7670',
    authDomain: 'notes-app-b7670.firebaseapp.com',
    storageBucket: 'notes-app-b7670.firebasestorage.app',
    measurementId: 'G-3C8VHQ39JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1U7C68HoZhitHZgZWfPZzwyy-0zAabG4',
    appId: '1:554766211865:android:9ded1f92dcf156aca90388',
    messagingSenderId: '554766211865',
    projectId: 'notes-app-b7670',
    storageBucket: 'notes-app-b7670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkCe7RNoi1ynDxQ0fTxrJ2GC4DplLqz_U',
    appId: '1:554766211865:ios:309d8c309b71f4bca90388',
    messagingSenderId: '554766211865',
    projectId: 'notes-app-b7670',
    storageBucket: 'notes-app-b7670.firebasestorage.app',
    iosClientId: '554766211865-fl8k5fj9m3lni2t57va9rgtar71h12t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkCe7RNoi1ynDxQ0fTxrJ2GC4DplLqz_U',
    appId: '1:554766211865:ios:309d8c309b71f4bca90388',
    messagingSenderId: '554766211865',
    projectId: 'notes-app-b7670',
    storageBucket: 'notes-app-b7670.firebasestorage.app',
    iosClientId: '554766211865-fl8k5fj9m3lni2t57va9rgtar71h12t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNfiWDgpT7qmcAlFG6DREFaru-NZOupkQ',
    appId: '1:554766211865:web:7362b8820b1abe62a90388',
    messagingSenderId: '554766211865',
    projectId: 'notes-app-b7670',
    authDomain: 'notes-app-b7670.firebaseapp.com',
    storageBucket: 'notes-app-b7670.firebasestorage.app',
    measurementId: 'G-E30G3EBDYE',
  );
}
